[tool.poetry]
name = "materials"
version = "0.1.19-OOP"
description = ""
authors = ["Andrey Nikolaevich Korenyuk <korenyuk.a.n@mail.ru>"]
license = "LICENSE.txt"
readme = "README.md"
packages = [{include = "materials"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.1"
logger = {path = "I:/Программирование/Pro0.5-logger_for_my_projects/dist/logger-0.1.3.tar.gz"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
