[tool.poetry]
name = "materials"
version = "0.1.49"
description = ""
authors = ["Andrey Nikolaevich Korenyuk <korenyuk.a.n@mail.ru>"]
license = "LICENSE.txt"
readme = "README.md"
packages = [{include = "materials"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.5.1"
service = {path = "I:/Программирование/Pro0.5-service_for_my_projects/dist/service-0.1.32.tar.gz"}
pydantic = "^1.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
